### ISSUE TITLE
[Windows] Som não para imediatamente

### ISSUE THREAD

**Issue by victorperin** [oloquinho/oloquinho#5]
Apenas no windows, mesmo depois de parar a aplicação, o som continua sendo executado.

**Comment by jcbombardelli** [comment]
Acho que essa é a ideia, não ?

**Comment by victorperin** [comment]
A idéia é poder parar o código imediatamente, pq realmente isso é muito irritante... uhauha

Mas percebemos esse problema durante o desenvolvimento. E apenas no Windows, no Mac e no Linux funciona normalmente.

Ah, adicionando também que ele executa o som apenas por uma execução dos arquivos de audio. Se alguém que manja mais de Windows puder investigar, eu agradeço. :)

**Comment by jcbombardelli** [comment]
Percebi que o mesmo acontece em projetos tipo o "omaewa", isso acontece pq quem está executando é o vbScript, pra finalizar precisaria encontrar o processo onde está esse script e encerra-lo também. 
Acho que é um problema sem solução se simplesmente dermos um "Control+C" na execução do "node index.js" mas talvez criar um "Press any Key to terminate" e ai sim procurar pelo processo do script e encerra-lo (não sei se com NodeJSisso é possivel).

O que acham ?

**Comment by victorperin** [comment]
É possível fazer graceful shutdown no NodeJS. Acredito que seja um caminho.

Além disso, pode ser que consiga resolver esse problema executando spawn no lugar do exec. Mas preciso estar em uma maquina windows pra testar isso.
